#!/usr/bin/env php
<?php

$rootPath = $dumpPath = '';

$args = $argv;
array_shift($args);

do {
    $arg = array_shift($args);
    switch ($arg) {
        case '--root':
            $rootPath = realpath(array_shift($args));
            break;
    }
} while ($arg !== null);

if (empty($rootPath)) {
    echo 'Usage: ', $argv[0], ' --root root_directory', PHP_EOL, 'Bye!', PHP_EOL;
    exit(1);
}

$dumpPath = $rootPath . '/build/database';
if (!is_dir($dumpPath)) {
    mkdir($dumpPath, 0700, true);
}
$dumpPath = realpath($dumpPath);

echo 'Removing all dump files... ';
$files = glob($dumpPath . '/*.dump.sql');
foreach ($files as $file) {
    unlink($file);
}
echo 'done', PHP_EOL;

require_once 'common.php';

$tables = Db::getInstance()->executeS('SHOW TABLES');
foreach ($tables as $table) {
    $table = current($table);
    echo $table, '...', PHP_EOL;
    $shellQuery = sprintf('mysqldump -h %s -u %s -p%s %s %s --skip-add-locks --skip-disable-keys --skip-comments > %s',
        _DB_SERVER_,
        _DB_USER_,
        _DB_PASSWD_,
        _DB_NAME_,
        $table,
        $dumpPath . '/' . $table . '.dump.sql'
    );
    shell_exec($shellQuery);
}
